import React, { useState, useEffect } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  Image,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
  Share,
} from 'react-native';
import Icon from 'react-native-vector-icons/MaterialCommunityIcons';
import { useNavigation, useRoute } from '@react-navigation/native';
import api from '../api/api';

export default function ReportDetailScreen() {
  const navigation = useNavigation();
  const route = useRoute();
  const { reportId } = route.params;

  const [loading, setLoading] = useState(true);
  const [report, setReport] = useState(null);

  useEffect(() => {
    fetchReportDetails();
  }, []);

  const fetchReportDetails = async () => {
    try {
      setLoading(true);
      const response = await api.get(`/reports/${reportId}`);
      setReport(response.data);
    } catch (error) {
      console.error('Failed to fetch report:', error);
      Alert.alert('Error', 'Failed to load report details');
    } finally {
      setLoading(false);
    }
  };

  const handleDownloadPDF = async () => {
    try {
      Alert.alert('Download', 'PDF download will be implemented in production');
      // In production: use react-native-fs to download PDF
    } catch (error) {
      Alert.alert('Error', 'Failed to download PDF');
    }
  };

  const handleShare = async () => {
    try {
      await Share.share({
        message: `Plant Health Report\n\nDisease: ${report.diagnosis}\nConfidence: ${(report.confidence * 100).toFixed(1)}%\n\nGenerated by Plant Health Diagnosis Tool`,
      });
    } catch (error) {
      console.error('Share error:', error);
    }
  };

  if (loading) {
    return (
      <View style={styles.loadingContainer}>
        <ActivityIndicator size="large" color="#4CAF50" />
        <Text style={styles.loadingText}>Loading report...</Text>
      </View>
    );
  }

  if (!report) {
    return (
      <View style={styles.errorContainer}>
        <Icon name="alert-circle" size={60} color="#F44336" />
        <Text style={styles.errorText}>Report not found</Text>
      </View>
    );
  }

  return (
    <ScrollView style={styles.container}>
      {/* Header Actions */}
      <View style={styles.headerActions}>
        <TouchableOpacity style={styles.actionButton} onPress={handleDownloadPDF}>
          <Icon name="download" size={24} color="#4CAF50" />
          <Text style={styles.actionText}>Download PDF</Text>
        </TouchableOpacity>
        <TouchableOpacity style={styles.actionButton} onPress={handleShare}>
          <Icon name="share-variant" size={24} color="#4CAF50" />
          <Text style={styles.actionText}>Share</Text>
        </TouchableOpacity>
      </View>

      {/* Plant Image */}
      {report.imageUrl && (
        <Image source={{ uri: report.imageUrl }} style={styles.plantImage} />
      )}

      {/* Report Header */}
      <View style={styles.reportCard}>
        <View style={styles.reportHeader}>
          <Icon name="file-document-check" size={32} color="#4CAF50" />
          <View style={styles.headerText}>
            <Text style={styles.reportTitle}>Detailed Analysis Report</Text>
            <Text style={styles.reportDate}>
              {new Date(report.createdAt).toLocaleDateString('en-IN', {
                year: 'numeric',
                month: 'long',
                day: 'numeric',
              })}
            </Text>
          </View>
        </View>
      </View>

      {/* Diagnosis Section */}
      <View style={styles.section}>
        <View style={styles.sectionHeader}>
          <Icon name="alert-decagram" size={24} color="#F44336" />
          <Text style={styles.sectionTitle}>Diagnosis</Text>
        </View>
        <View style={styles.diagnosisCard}>
          <Text style={styles.diagnosisName}>{report.diagnosis}</Text>
          <View style={styles.confidenceContainer}>
            <Text style={styles.confidenceLabel}>Confidence:</Text>
            <View style={styles.confidenceBar}>
              <View
                style={[
                  styles.confidenceFill,
                  { width: `${(report.confidence || 0) * 100}%` },
                ]}
              />
            </View>
            <Text style={styles.confidenceText}>
              {((report.confidence || 0) * 100).toFixed(1)}%
            </Text>
          </View>
          {report.severity && (
            <View style={styles.severityTag}>
              <Text style={styles.severityText}>Severity: {report.severity}</Text>
            </View>
          )}
        </View>
      </View>

      {/* Plant Information */}
      {report.plantSpecies && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Icon name="leaf" size={24} color="#4CAF50" />
            <Text style={styles.sectionTitle}>Plant Information</Text>
          </View>
          <View style={styles.infoCard}>
            <InfoRow label="Species" value={report.plantSpecies} />
            {report.scientificName && (
              <InfoRow label="Scientific Name" value={report.scientificName} />
            )}
            {report.family && (
              <InfoRow label="Family" value={report.family} />
            )}
          </View>
        </View>
      )}

      {/* Symptoms */}
      {report.symptoms && report.symptoms.length > 0 && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Icon name="stethoscope" size={24} color="#FF9800" />
            <Text style={styles.sectionTitle}>Identified Symptoms</Text>
          </View>
          <View style={styles.listCard}>
            {report.symptoms.map((symptom, index) => (
              <View key={index} style={styles.listItem}>
                <Icon name="circle-small" size={20} color="#FF9800" />
                <Text style={styles.listItemText}>{symptom}</Text>
              </View>
            ))}
          </View>
        </View>
      )}

      {/* Treatment Plan */}
      {report.treatmentPlan && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Icon name="medical-bag" size={24} color="#2196F3" />
            <Text style={styles.sectionTitle}>Treatment Plan</Text>
          </View>
          <View style={styles.treatmentCard}>
            {report.treatmentPlan.immediate && (
              <TreatmentStep
                title="Immediate Action"
                steps={report.treatmentPlan.immediate}
                color="#F44336"
              />
            )}
            {report.treatmentPlan.shortTerm && (
              <TreatmentStep
                title="Short-term (1-2 weeks)"
                steps={report.treatmentPlan.shortTerm}
                color="#FF9800"
              />
            )}
            {report.treatmentPlan.longTerm && (
              <TreatmentStep
                title="Long-term Care"
                steps={report.treatmentPlan.longTerm}
                color="#4CAF50"
              />
            )}
          </View>
        </View>
      )}

      {/* Organic Remedies */}
      {report.organicRemedies && report.organicRemedies.length > 0 && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Icon name="flower" size={24} color="#9C27B0" />
            <Text style={styles.sectionTitle}>Organic Remedies</Text>
          </View>
          <View style={styles.remediesCard}>
            {report.organicRemedies.map((remedy, index) => (
              <View key={index} style={styles.remedyItem}>
                <Text style={styles.remedyName}>{remedy.name}</Text>
                <Text style={styles.remedyDescription}>{remedy.description}</Text>
                {remedy.howToUse && (
                  <Text style={styles.remedyUsage}>How to use: {remedy.howToUse}</Text>
                )}
              </View>
            ))}
          </View>
        </View>
      )}

      {/* Prevention Tips */}
      {report.preventionTips && report.preventionTips.length > 0 && (
        <View style={styles.section}>
          <View style={styles.sectionHeader}>
            <Icon name="shield-check" size={24} color="#4CAF50" />
            <Text style={styles.sectionTitle}>Prevention Tips</Text>
          </View>
          <View style={styles.listCard}>
            {report.preventionTips.map((tip, index) => (
              <View key={index} style={styles.listItem}>
                <Icon name="check" size={20} color="#4CAF50" />
                <Text style={styles.listItemText}>{tip}</Text>
              </View>
            ))}
          </View>
        </View>
      )}

      {/* Need More Help */}
      <View style={styles.helpCard}>
        <Text style={styles.helpTitle}>Still need help?</Text>
        <Text style={styles.helpDescription}>
          Connect with a certified agronomist for personalized guidance
        </Text>
        <TouchableOpacity
          style={styles.consultButton}
          onPress={() =>
            navigation.navigate('Payment', {
              amount: 199,
              type: 'consultation',
              analysisId: report._id,
              imageUri: report.imageUrl,
            })
          }
        >
          <Icon name="chat" size={20} color="#fff" />
          <Text style={styles.consultButtonText}>Chat with Expert (₹199)</Text>
        </TouchableOpacity>
      </View>
    </ScrollView>
  );
}

const InfoRow = ({ label, value }) => (
  <View style={styles.infoRow}>
    <Text style={styles.infoLabel}>{label}:</Text>
    <Text style={styles.infoValue}>{value}</Text>
  </View>
);

const TreatmentStep = ({ title, steps, color }) => (
  <View style={styles.treatmentStep}>
    <View style={[styles.stepIndicator, { backgroundColor: color }]} />
    <View style={styles.stepContent}>
      <Text style={styles.stepTitle}>{title}</Text>
      {steps.map((step, index) => (
        <View key={index} style={styles.stepItem}>
          <Text style={styles.stepNumber}>{index + 1}.</Text>
          <Text style={styles.stepText}>{step}</Text>
        </View>
      ))}
    </View>
  </View>
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F5F5',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5F5F5',
  },
  loadingText: {
    marginTop: 16,
    fontSize: 16,
    color: '#666',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    fontSize: 18,
    color: '#F44336',
    marginTop: 16,
  },
  headerActions: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  actionButton: {
    alignItems: 'center',
    gap: 6,
  },
  actionText: {
    fontSize: 12,
    color: '#4CAF50',
    fontWeight: '600',
  },
  plantImage: {
    width: '100%',
    height: 250,
    backgroundColor: '#E0E0E0',
  },
  reportCard: {
    backgroundColor: '#fff',
    padding: 20,
  },
  reportHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  headerText: {
    flex: 1,
  },
  reportTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
  },
  reportDate: {
    fontSize: 14,
    color: '#666',
    marginTop: 4,
  },
  section: {
    marginTop: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 16,
    marginBottom: 12,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  diagnosisCard: {
    backgroundColor: '#fff',
    padding: 20,
    marginHorizontal: 16,
    borderRadius: 12,
  },
  diagnosisName: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#F44336',
    marginBottom: 12,
  },
  confidenceContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  confidenceLabel: {
    fontSize: 14,
    color: '#666',
  },
  confidenceBar: {
    flex: 1,
    height: 8,
    backgroundColor: '#E0E0E0',
    borderRadius: 4,
    overflow: 'hidden',
  },
  confidenceFill: {
    height: '100%',
    backgroundColor: '#4CAF50',
  },
  confidenceText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#4CAF50',
  },
  severityTag: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFF3E0',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    marginTop: 12,
  },
  severityText: {
    fontSize: 14,
    color: '#FF9800',
    fontWeight: '600',
  },
  infoCard: {
    backgroundColor: '#fff',
    padding: 16,
    marginHorizontal: 16,
    borderRadius: 12,
  },
  infoRow: {
    flexDirection: 'row',
    paddingVertical: 8,
  },
  infoLabel: {
    fontSize: 14,
    color: '#666',
    width: 130,
  },
  infoValue: {
    flex: 1,
    fontSize: 14,
    color: '#333',
    fontWeight: '500',
  },
  listCard: {
    backgroundColor: '#fff',
    padding: 16,
    marginHorizontal: 16,
    borderRadius: 12,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 10,
  },
  listItemText: {
    flex: 1,
    fontSize: 14,
    color: '#333',
    lineHeight: 20,
  },
  treatmentCard: {
    backgroundColor: '#fff',
    padding: 16,
    marginHorizontal: 16,
    borderRadius: 12,
  },
  treatmentStep: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  stepIndicator: {
    width: 4,
    borderRadius: 2,
    marginRight: 12,
  },
  stepContent: {
    flex: 1,
  },
  stepTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
  },
  stepItem: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  stepNumber: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4CAF50',
    marginRight: 8,
  },
  stepText: {
    flex: 1,
    fontSize: 14,
    color: '#333',
    lineHeight: 20,
  },
  remediesCard: {
    backgroundColor: '#fff',
    padding: 16,
    marginHorizontal: 16,
    borderRadius: 12,
  },
  remedyItem: {
    marginBottom: 16,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#E0E0E0',
  },
  remedyName: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#9C27B0',
    marginBottom: 6,
  },
  remedyDescription: {
    fontSize: 14,
    color: '#333',
    lineHeight: 20,
    marginBottom: 6,
  },
  remedyUsage: {
    fontSize: 13,
    color: '#666',
    fontStyle: 'italic',
  },
  helpCard: {
    backgroundColor: '#E3F2FD',
    margin: 16,
    padding: 20,
    borderRadius: 12,
    alignItems: 'center',
  },
  helpTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1976D2',
    marginBottom: 8,
  },
  helpDescription: {
    fontSize: 14,
    color: '#1565C0',
    textAlign: 'center',
    marginBottom: 16,
  },
  consultButton: {
    flexDirection: 'row',
    backgroundColor: '#2196F3',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderRadius: 25,
    alignItems: 'center',
    gap: 8,
  },
  consultButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
});
